StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{62DF4507DA5F121F}" {
   Id "STR-Ammo-Caliber-23x152mmB"
   Target_en_us "23x152mmB"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1658800968
   Author "mikia"
   LastChanged "mikia"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62DF4507D2F9D0C8}" {
   Id "STR-Ammo-ID-BZT"
   Target_en_us "BZT"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1658800968
   Author "mikia"
   LastChanged "mikia"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62DF4507D49B761A}" {
   Id "STR-Ammo-ID-OFZT"
   Target_en_us "OFZT"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1658800968
   Author "mikia"
   LastChanged "mikia"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62DF4506FB1C359B}" {
   Id "STR-Ammo-Type-APIT"
   Target_en_us "APIT"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1658800968
   Author "mikia"
   LastChanged "mikia"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62DF4506C4CE8464}" {
   Id "STR-Ammo-Type-HEFT"
   Target_en_us "HEFT"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1658800968
   Author "mikia"
   LastChanged "mikia"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62DF42026E1ADD7D}" {
   Id "STR-EditableEntity-Vehicle-ZSU-23-4M2_Name"
   Target_en_us "ZSU-23-4M2 \"Shilka\""
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1705995356
   Author "mikia"
   LastChanged "mikia"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{65AF6C17B8EE9A7F}" {
   Id "STR-EditableEntity-Vehicle-ZSU-23-4M3_Name"
   Target_en_us "ZSU-23-4M3 \"Shilka\""
   Modified 1705995367
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{65AF6C17BBD6AF03}" {
   Id "STR-EditableEntity-Vehicle-ZSU-23-4M4_Name"
   Target_en_us "ZSU-23-4M4 \"Strelets"
   Modified 1705995436
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{62E14EDE38CE7FD5}" {
   Id "STR-Vehicle-Radar"
   Target_en_us "Radar"
   Modified 1658933507
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{62DF4507AFC851E2}" {
   Id "STR-Vehicle-Weapon-AZP23"
   Target_en_us "AZP-23"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1658800968
   Author "mikia"
   LastChanged "mikia"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62DF45061327BDDA}" {
   Id "STR-Vehicle-Weapon-AZP23-Magazine-Description"
   Target_en_us "4x 500 round Steel Cased 23x152mmB magazines loaded with OFZT High Explosive Fragmentation Tracer and BZT Armor Piercing Incendiary Tarcers."
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1658800968
   Author "mikia"
   LastChanged "mikia"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62DF45061EBD763E}" {
   Id "STR-Vehicle-Weapon-AZP23-Magazine-Name"
   Target_en_us "23x152mm AZP-23 belt"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1693152038
   Author "mikia"
   LastChanged "SpaceStrider"
   ImageLink ""
   Hidden 0
  }
 }
}